export const unicodeCodes = {
    LEFT_TO_RIGHT_EMBEDDING: "\u202A",
    RIGHT_TO_LEFT_EMBEDDING: "\u202B",
    POP_DIRECTIONAL_FORMATTING: "\u202C",

    // LEFT_TO_RIGHT_ISOLATE: "\u2066",
    // RIGHT_TO_LEFT_ISOLATE: "\u2067",
    // POP_DIRECTIONAL_ISOLATE: "\u2069",
};
