const LEFT_TO_RIGHT_EMBEDDING: string = "\u202A";
const RIGHT_TO_LEFT_EMBEDDING: string = "\u202B";
const POP_DIRECTIONAL_FORMATTING: string = "\u202C";

const LEFT_TO_RIGHT_ISOLATE: string = "\u2066";
const RIGHT_TO_LEFT_ISOLATE: string = "\u2067";
const POP_DIRECTIONAL_ISOLATE: string = "\u2069";

export default {
    LEFT_TO_RIGHT_EMBEDDING: LEFT_TO_RIGHT_EMBEDDING,
    RIGHT_TO_LEFT_EMBEDDING: RIGHT_TO_LEFT_EMBEDDING,
    POP_DIRECTIONAL_FORMATTING: POP_DIRECTIONAL_FORMATTING,
    LEFT_TO_RIGHT_ISOLATE: LEFT_TO_RIGHT_ISOLATE,
    RIGHT_TO_LEFT_ISOLATE: RIGHT_TO_LEFT_ISOLATE,
    POP_DIRECTIONAL_ISOLATE: POP_DIRECTIONAL_ISOLATE
};