const LEFT_TO_RIGHT_EMBEDDING: string = "\u202A";
const RIGHT_TO_LEFT_EMBEDDING: string = "\u202B";
const POP_DIRECTIONAL_FORMATTING: string = "\u202C";

export default {
    LEFT_TO_RIGHT_EMBEDDING: LEFT_TO_RIGHT_EMBEDDING,
    RIGHT_TO_LEFT_EMBEDDING: RIGHT_TO_LEFT_EMBEDDING,
    POP_DIRECTIONAL_FORMATTING: POP_DIRECTIONAL_FORMATTING,
};